/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXEC = 5;
  /** RegularExpression Id. */
  int NEW = 6;
  /** RegularExpression Id. */
  int VAR = 7;
  /** RegularExpression Id. */
  int MACRO = 8;
  /** RegularExpression Id. */
  int TURNTOMY = 9;
  /** RegularExpression Id. */
  int TURNTOTHE = 10;
  /** RegularExpression Id. */
  int WALK = 11;
  /** RegularExpression Id. */
  int JUMP = 12;
  /** RegularExpression Id. */
  int DROP = 13;
  /** RegularExpression Id. */
  int PICK_NEW = 14;
  /** RegularExpression Id. */
  int GRAB = 15;
  /** RegularExpression Id. */
  int LETGO = 16;
  /** RegularExpression Id. */
  int POP_NEW = 17;
  /** RegularExpression Id. */
  int MOVES = 18;
  /** RegularExpression Id. */
  int NOP = 19;
  /** RegularExpression Id. */
  int SAFEEXE = 20;
  /** RegularExpression Id. */
  int RIGHT = 21;
  /** RegularExpression Id. */
  int LEFT = 22;
  /** RegularExpression Id. */
  int BACK = 23;
  /** RegularExpression Id. */
  int FRONT = 24;
  /** RegularExpression Id. */
  int FORWARD = 25;
  /** RegularExpression Id. */
  int BACKWARDS = 26;
  /** RegularExpression Id. */
  int NORTH = 27;
  /** RegularExpression Id. */
  int SOUTH = 28;
  /** RegularExpression Id. */
  int EAST = 29;
  /** RegularExpression Id. */
  int WEST = 30;
  /** RegularExpression Id. */
  int SIZE = 31;
  /** RegularExpression Id. */
  int MYX = 32;
  /** RegularExpression Id. */
  int MYY = 33;
  /** RegularExpression Id. */
  int MYCHIPS = 34;
  /** RegularExpression Id. */
  int MYBALLOONS = 35;
  /** RegularExpression Id. */
  int BALLOONSHERE = 36;
  /** RegularExpression Id. */
  int CHIPSHERE = 37;
  /** RegularExpression Id. */
  int ROOMFORCHIPS = 38;
  /** RegularExpression Id. */
  int IF = 39;
  /** RegularExpression Id. */
  int THEN = 40;
  /** RegularExpression Id. */
  int ELSE = 41;
  /** RegularExpression Id. */
  int FI = 42;
  /** RegularExpression Id. */
  int DO = 43;
  /** RegularExpression Id. */
  int OD = 44;
  /** RegularExpression Id. */
  int REPEAT = 45;
  /** RegularExpression Id. */
  int TIMES = 46;
  /** RegularExpression Id. */
  int PER = 47;
  /** RegularExpression Id. */
  int ISBLOCKED = 48;
  /** RegularExpression Id. */
  int ISFACING = 49;
  /** RegularExpression Id. */
  int ZERO = 50;
  /** RegularExpression Id. */
  int NOT = 51;
  /** RegularExpression Id. */
  int WORD = 52;
  /** RegularExpression Id. */
  int LETTER = 53;
  /** RegularExpression Id. */
  int BALLOONS = 54;
  /** RegularExpression Id. */
  int CHIPS = 55;
  /** RegularExpression Id. */
  int NUM = 56;
  /** RegularExpression Id. */
  int DIGIT = 57;
  /** RegularExpression Id. */
  int SEMI = 58;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"EXEC\"",
    "\"NEW\"",
    "\"VAR\"",
    "\"MACRO\"",
    "\"turnToMy\"",
    "\"turnToThe\"",
    "\"walk\"",
    "\"jump\"",
    "\"drop\"",
    "\"pick\"",
    "\"grab\"",
    "\"letGo\"",
    "\"pop\"",
    "\"moves\"",
    "\"nop\"",
    "\"safeExe\"",
    "\"right\"",
    "\"left\"",
    "\"back\"",
    "\"front\"",
    "\"forward\"",
    "\"backwards\"",
    "\"North\"",
    "\"South\"",
    "\"East\"",
    "\"West\"",
    "\"size\"",
    "\"myX\"",
    "\"myY\"",
    "\"myChips\"",
    "\"myBalloons\"",
    "\"balloonsHere\"",
    "\"chipsHere\"",
    "\"roomForChips\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"fi\"",
    "\"do\"",
    "\"od\"",
    "\"repeat\"",
    "\"times\"",
    "\"per\"",
    "\"isBlocked?\"",
    "\"isFacing?\"",
    "\"zero?\"",
    "\"not\"",
    "<WORD>",
    "<LETTER>",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUM>",
    "<DIGIT>",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=\"",
  };

}
