/* Generated By:JavaCC: Do not edit this line. ParserPrologConstants.java */
package uniandes.lym.parserJavaCC.parserProlog;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserPrologConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARROW = 5;
  /** RegularExpression Id. */
  int CH = 6;
  /** RegularExpression Id. */
  int QUOTED = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int UPPER = 10;
  /** RegularExpression Id. */
  int LOWER = 11;
  /** RegularExpression Id. */
  int VAR = 12;
  /** RegularExpression Id. */
  int ATOM = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":-\"",
    "<CH>",
    "<QUOTED>",
    "<INT>",
    "<DIGIT>",
    "<UPPER>",
    "<LOWER>",
    "<VAR>",
    "<ATOM>",
    "\",\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"|\"",
    "\"]\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
