/* Generated By:JavaCC: Do not edit this line. PetriParserConstants.java */
package uniandes.lym.parserJavaCC.petriParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PetriParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PN = 5;
  /** RegularExpression Id. */
  int END = 6;
  /** RegularExpression Id. */
  int PLACES = 7;
  /** RegularExpression Id. */
  int TRANSITIONS = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int LETTER = 10;
  /** RegularExpression Id. */
  int NAME = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"PetriNet\"",
    "\"End\"",
    "\"Places\"",
    "\"Transitions\"",
    "<DIGIT>",
    "<LETTER>",
    "<NAME>",
    "<NUMBER>",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
  };

}
