/* Generated By:JavaCC: Do not edit this line. GraphParserConstants.java */
package uniandes.lym.parserJavaCC.graphParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GraphParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GRAPH = 5;
  /** RegularExpression Id. */
  int NODES = 6;
  /** RegularExpression Id. */
  int ARCS = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int LETTER = 9;
  /** RegularExpression Id. */
  int NAME = 10;
  /** RegularExpression Id. */
  int NUMBER = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"graph\"",
    "\"nodes\"",
    "\"arcs\"",
    "<DIGIT>",
    "<LETTER>",
    "<NAME>",
    "<NUMBER>",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\";\"",
    "\":\"",
    "\"&\"",
    "\"-\"",
    "\"<\"",
    "\">\"",
  };

}
