/* Generated By:JavaCC: Do not edit this line. ExprParserConstants.java */
package uniandes.lym.parserJavaCC.exprParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExprParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 5;
  /** RegularExpression Id. */
  int HEXA = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int LETTER = 8;
  /** RegularExpression Id. */
  int WRITE = 9;
  /** RegularExpression Id. */
  int SQR = 10;
  /** RegularExpression Id. */
  int END = 11;
  /** RegularExpression Id. */
  int VAR = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<INT>",
    "<HEXA>",
    "<DIGIT>",
    "<LETTER>",
    "\"write\"",
    "\"SQR\"",
    "\"end\"",
    "<VAR>",
    "\"=\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
