/* Generated By:JavaCC: Do not edit this line. stackParserConstants.java */
package uniandes.lym.parserJavaCC.stackParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface stackParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 4;
  /** RegularExpression Id. */
  int HEXA = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int WRITE = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int PUSH = 10;
  /** RegularExpression Id. */
  int TIMES = 11;
  /** RegularExpression Id. */
  int ASG = 12;
  /** RegularExpression Id. */
  int END = 13;
  /** RegularExpression Id. */
  int VAR = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<INT>",
    "<HEXA>",
    "<DIGIT>",
    "<LETTER>",
    "\"write\"",
    "\"PLUS\"",
    "\"PUSH\"",
    "\"TIMES\"",
    "\"ASG\"",
    "\"END\"",
    "<VAR>",
    "\"\\n\"",
  };

}
