/* Generated By:JavaCC: Do not edit this line. S_ExpParserConstants.java */
package uniandes.lym.parserJavaCC.sExpParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface S_ExpParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int NAME = 7;
  /** RegularExpression Id. */
  int NUM = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<DIGIT>",
    "<LETTER>",
    "<NAME>",
    "<NUM>",
    "\"(\"",
    "\"+\"",
    "\"*\"",
    "\")\"",
  };

}
